# Generated by Django 4.2.13 on 2024-05-16 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='agree_count',
            new_name='agree',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='disagree_count',
            new_name='disagree',
        ),
    ]
